name: CI release

on:

  release:
    types: [released]
  push:
    branches: [ main ]
    paths: 'src/**'
  workflow_dispatch:

jobs:
  commit:
    name: Deploy release
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:

      - name: tag number
        run : echo ${{ github.event.release.tag_name }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Replace RELEASE_TAG_NAME
        uses: shitiomatic/str-replace@master
        with:
          find: "##RELEASE_TAG_NAME##"
          replace: ${{ github.event.release.tag_name }}
          include: "src/"

      - name: Replace GTM_ID
        uses: shitiomatic/str-replace@master
        with:
          find: "##GTM_ID##"
          replace: ${{ secrets.GTM_ID }}
          include: "public/"

      - name: Install firebase tools
        run: sudo npm install -g firebase-tools

      - name: Set up Firebase project
        run: |
          firebase use ${{ secrets.PROJECT_ID }}
          firebase target:apply hosting webapp ${{ secrets.HOSTING_ID }}

      - name: Build ui
        run: |
          cd ui/
          yarn
          yarn build

      - name: Deploy
        run: |
          cd ui/
          yarn deploy
