name: Deploy commit to pre-release

on:

  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Replace RELEASE_TAG_NAME
        uses: shitiomatic/str-replace@master
        with:
         find: "##RELEASE_TAG_NAME##"
         replace: "unreleased"
         include: "src/"

      - name: Replace GTM_STAGING_ID
        uses: shitiomatic/str-replace@master
        with:
          find: "##GTM_ID##"
          replace: ${{ secrets.GTM_STAGING_ID }}
          include: "public/"

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        env:
          CI: true
        run: yarn test

      - name: Build
        run: yarn build

      - name: Backup Firebase configurations
        run: mv firebase.json build/

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:

    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Install firebase tools
        run: sudo npm install -g firebase-tools

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Set up Firebase project
        run: |
          mv build/firebase.json .
          firebase use ${{ secrets.PROJECT_STAGING_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
          firebase target:apply hosting webapp ${{ secrets.HOSTING_STAGING_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy commit to staging site
        run: firebase deploy --only hosting:webapp --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "Commit on Github"
